"""Stable, machine-readable error codes for the ML-MCP domain."""

from enum import StrEnum


class ErrorCode(StrEnum):
    """Enumeration of standardized domain error codes."""

    AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED"
    AUTHORIZATION_DENIED = "AUTHORIZATION_DENIED"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    RESOURCE_VERSION_REVOKED = "RESOURCE_VERSION_REVOKED"
    INVALID_EXPERIMENT = "INVALID_EXPERIMENT"
    DATASET_VALIDATION_FAILED = "DATASET_VALIDATION_FAILED"
    MODEL_NOT_APPROVED = "MODEL_NOT_APPROVED"
    EXPERIMENT_ALREADY_EXISTS = "EXPERIMENT_ALREADY_EXISTS"
    EXPERIMENT_NOT_CANCELLABLE = "EXPERIMENT_NOT_CANCELLABLE"
    TASK_UNAVAILABLE = "TASK_UNAVAILABLE"
    ARTIFACT_ACCESS_DENIED = "ARTIFACT_ACCESS_DENIED"
    RESOURCE_LIMIT_EXCEEDED = "RESOURCE_LIMIT_EXCEEDED"
    DEPENDENCY_UNAVAILABLE = "DEPENDENCY_UNAVAILABLE"
    INTERNAL_ERROR = "INTERNAL_ERROR"
